### ISSUE TITLE
Clarify why files are recovered and, perhaps, their state

### ISSUE THREAD

**Issue by jennybc** [jmcphers/rsrecovr#1]
I appreciate this package! Just used it to rescue some Untitled's lost after a hard crash.

I was somewhat surprised to find lots of other files in the folder of recovered files. Why are *they* here and do I need to diff them against my current version?

In Slack you've now cleared this up:

> the dump is basically the set of open tabs you have, one file per tab

It would be helpful to know this. We also talked about whether we could narrow the set down to files that had unsaved changes. It's unclear if that is possible / worth it.

Finally, I liked this idea you had:

> Perhaps it’d be more helpful to make folders (“saved”, “unsaved”, “untitled”)

**Comment by jmcphers** [comment]
We now make "saved" folders for files that don't differ from their contents on disk, and "unsaved" for everything else.
