### ISSUE TITLE
Workflow re: securing the recovered files

### ISSUE THREAD

**Issue by jennybc** [jmcphers/rsrecovr#2]
Currently recovered files are written to a subdirectory below the R session temp dir.

I personally managed to lose them again by restarting R. Luckily you can just run `recover()` again. But I imagine that won't work once you've, for example, started to create new Untitled's?

Does it make sense to offer to write to a less perishable place? I think you can pretty much count on being in an interactive session with a highly motivated user, who will be happy to select from a couple choices (e.g. subdir of temp dir vs. project dir).

**Comment by jmcphers** [comment]
It does. I have updated this so that it writes to the project folder itself, in a `recovered_XXX` folder.
